function DriveTrainLog202002151001 = GetDriveTrainLogTable_v2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DRIVETRAINLOG202002151001 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  DRIVETRAINLOG202002151001 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DriveTrainLog202002151001 = importfile("C:\Users\agpri\OneDrive\Documents\FRC\FRC_2020\GIT\Matlab_2020\DriveTrain_DataLogging\DriveTrainLog_2020-02-15_10_01.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Feb-2020 10:09:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "LeftVelocityCommand", "RightVelocityCommand", "LeftActualVelocity", "RightActualVelocity", "LeftLeadAppliedOutput", "LeftFollowAppliedOutput", "RightLeadAppliedOutput", "RightFollowAppliedOutput", "LeftLeadVoltage", "LeftFollowVoltage", "RightLeadVoltage", "RightFollowVoltage", "LeftLeadCurrent", "LeftFollowCurrent", "RightLeadCurrent", "RightFollowCurrent", "VarName18"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName18", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName18", "EmptyFieldRule", "auto");

% Import the data
DriveTrainLog202002151001 = readtable(filename, opts);

end