function data = GetShooterLogTable(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SHOOTERLOG202003101902 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  SHOOTERLOG202003101902 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ShooterLog202003101902 = importfile("C:\Users\GEH-Magnet School 1\Documents\MATLAB\Matlab_2020\Shooter_DataLogging\ShooterLog_2020-03-10_19_02.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Mar-2020 18:09:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "MatchTime", "LeadRPM", "RPMSetpoint", "LeadAppliedOutput", "LeadBusVoltage", "LeadCurrent"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

end